version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 99
  reviewers:
  - dsyncerek
  assignees:
  - dsyncerek
  ignore:
  - dependency-name: concurrently
    versions:
    - 6.0.0
    - 6.0.1
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.2
    - 5.1.3
    - 5.2.0
- package-ecosystem: npm
  directory: "/client"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 99
  reviewers:
  - dsyncerek
  assignees:
  - dsyncerek
  ignore:
  - dependency-name: "@angular-devkit/build-angular"
    versions:
    - 0.1101.1
    - 0.1101.2
    - 0.1101.4
    - 0.1102.1
    - 0.1102.2
    - 0.1102.3
    - 0.1102.4
    - 0.1102.5
    - 0.1102.7
    - 0.1102.8
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
    - 8.1.0
  - dependency-name: "@angular/cli"
    versions:
    - 11.2.1
  - dependency-name: "@ngrx/schematics"
    versions:
    - 11.0.0
- package-ecosystem: npm
  directory: "/server"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 99
  reviewers:
  - dsyncerek
  assignees:
  - dsyncerek
  ignore:
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
    - 8.1.0
  - dependency-name: typeorm
    versions:
    - 0.2.30
  - dependency-name: class-transformer
    versions:
    - 0.3.2
