version: "3"

services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - .env
      
  adminer:
    image: adminer
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - postgres
